public with sharing class QueryTraining {
    
    //<<<<< USO DAS DIVERSAS CLÁSULAS >>>>>

    //Exemplo de query ordenada por um campo colocando os camps null por último 
    //Exemplo de query que ignora os primeiros X registros da consulta (OFFSET) 
    //Exemplo de query com o uso de IN com lista de valaores
    //Exemplo de query com o uso do LIKE e caractere coringa
    //Exemplo de query agrupada por grupo
    //Exemplo de query que permite o rastreio de campos visualizados para auditoria
    //Exemplo de query que bloqueia os registros no momento da transação
    /*Exemplo de query que força a consulta a respeitar todas as configurações de segurança,
    mesmo que a classe seja without sharing */

    //<<<<< CONSULTAS AGREGADAS >>>>>
}